language: java
jdk: openjdk7

before_install:
- sudo apt-get install -qq ruby ruby-dev build-essential rubygems
- sudo gem install fpm

script: 
- ./gradlew test
- ./gradlew distTar distZip debian

env:
- TERM=dumb PATH="$PATH:/usr/local/bin"
