language: java
jdk: openjdk7

before_install:
- sudo apt-get install -qq ruby ruby-dev build-essential rubygems
- sudo gem install travis bundler fpm
- fpm --help | grep "This is fpm" 

script: 
- ./gradlew test installApp distTar distZip debian

env:
- TERM=dumb PATH="$PATH:/usr/local/bin"

notifications:
  email: false
